layers:
  booking:
    - example.booking
  commands:
    - example.commands
  customer:
    - example.customer
  payments:
    - example.payments
  products:
    - example.products
  prices:
    - example.products.prices
  account:
    - example.customer.account

whitelist:
  booking: ~
  commands: ~
  customer: ~
  payments: ~
  products: ~
  prices: ~
  account: ~
