stages:
  - test
  - quality

image: python:3.9.1-slim-buster

before_script:
  - apt-get update
  - apt-get install -y curl git build-essential shellcheck
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - export PATH="/root/.poetry/bin:$PATH"
  - poetry install -n


unit_tests:
  stage: test
  script:
    - poetry run coverage run --source depcheck -m pytest --junitxml=report.xml
    - poetry run coverage report
    - poetry run coverage xml

yaml_linter:
  stage: quality
  script:
    - poetry run yamllint .
  rules:
    - changes: ['.*.yml', '*.yml', '**/*.yml', '**/.*.yml']
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

type_hinting:
  stage: quality
  script:
    - poetry run pyre check

code_quality:
  stage: quality
  script:
    - poetry run flake8 depcheck
